name: Publish

on:
  push:
    branches: [ master, dev ]

jobs:
  bump-npm-version:
    if: github.actor != 'vikelabs-bot'
    needs: [ lint, build, test ]
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Configure CI Git User
        run: |
          git config --global user.name 'vikelabs-bot'
          git config --global user.email 'vikelabs-bot-github@vikelabs.ca'

      - name: Bump minor version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    # need conditional so publishing is done after bot commits version bump
    if: github.actor == 'vikelabs-bot'
    needs: [ lint, build, test ]
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress

      - name: Create .npmrc for auth token publishing
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          # token must be generated by admin account to vikelabs org, currently gnomi
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build and publish npm package
        run: npm run build && npm publish --access public